name: Run automated fix

on:
  workflow_call:

jobs:
  fix:
    name: Run automated fix
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      #  RUNNER_DEBUG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn

      - name: Run fix script
        run: yarn fix || exit 0

      - name: Apply automated fix
        uses: autofix-ci/action@v1
        with:
          commit-message: "Apply automated changes"
          fail-fast: false
