name: Run code fix script

on:
  workflow_call:

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn

      - name: Run fix script
        run: yarn fix

      - uses: autofix-ci/action@v1
        env:
          RUNNER_DEBUG: "1"
        with:
          commit-message: "Apply automated changes"
          fail-fast: false
