name: Run scheduled task

on:
  workflow_call:

jobs:
  scheduled:
    name: Run scheduled task
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      #  RUNNER_DEBUG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn

      - name: Run script
        run: yarn update

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update
          branch: automated-update
          branch-suffix: timestamp
          title: Update
