name: Run code fix script

on:
  workflow_call:

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Run fix script
        run: yarn fix

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
        with:
          commit-message: "Apply automated changes"